<?php

/**
 * @file
 * Contains custom_site_info.module.
 */

/**
 * Implements hook_form_alter().
 */
function custom_site_info_form_alter(&$form, &$form_state, $form_id) {
    // Get site api key from configuration
    $site_api_key = \Drupal::config('system.site')->get('siteapikey');
    // Change submit button label if form id is custom_site_info_form and site api key is entered.
    if ($form_id == 'custom_site_info_form' && $site_api_key) {
        $form['actions']['submit']['#value'] = t('Update Configuration');
    }
  }

/**
 * Implements hook_uninstall().
 */
function custom_site_info_uninstall() {
    \Drupal::configFactory()->getEditable('system.site')->clear('siteapikey')->save();
  }
